// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACx6H4lUVhUdfRi5GIlMD5MqXQ8y9nb5A',
    appId: '1:25465352063:web:c8ba491297bf8fd28cf44a',
    messagingSenderId: '25465352063',
    projectId: 'bookly-25b7e',
    authDomain: 'bookly-25b7e.firebaseapp.com',
    storageBucket: 'bookly-25b7e.appspot.com',
    measurementId: 'G-CV44HSDJZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Cl-n1bHJnbgvYBI6B0zk0I-8BL_bSI4',
    appId: '1:25465352063:android:9017cd6689028a468cf44a',
    messagingSenderId: '25465352063',
    projectId: 'bookly-25b7e',
    storageBucket: 'bookly-25b7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqTFykHV2RS2j-kcDBrGO8sY6IdMtsDco',
    appId: '1:25465352063:ios:37d297e73fded3488cf44a',
    messagingSenderId: '25465352063',
    projectId: 'bookly-25b7e',
    storageBucket: 'bookly-25b7e.appspot.com',
    iosClientId: '25465352063-q3e5qv67j14nh5vua3ee8420ccni7dgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqTFykHV2RS2j-kcDBrGO8sY6IdMtsDco',
    appId: '1:25465352063:ios:37d297e73fded3488cf44a',
    messagingSenderId: '25465352063',
    projectId: 'bookly-25b7e',
    storageBucket: 'bookly-25b7e.appspot.com',
    iosClientId: '25465352063-q3e5qv67j14nh5vua3ee8420ccni7dgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly',
  );
}
